export const contentResponseSchema = {
  type: "object",
  additionalProperties: false,
  required: ["titles", "hooks", "caption", "sellingPoints", "hashtags", "poster"],
  properties: {
    titles: {
      type: "array",
      minItems: 3,
      items: scoredLineSchema()
    },
    hooks: {
      type: "array",
      minItems: 2,
      items: scoredLineSchema()
    },
    caption: {
      type: "string"
    },
    sellingPoints: {
      type: "array",
      items: { type: "string" }
    },
    hashtags: {
      type: "array",
      items: { type: "string" }
    },
    poster: {
      type: "object",
      additionalProperties: false,
      required: ["headline", "subtitle", "cta", "style"],
      properties: {
        headline: { type: "string" },
        subtitle: { type: "string" },
        cta: { type: "string" },
        style: {
          type: "string",
          enum: ["Clean", "Bold", "Soft", "Editorial"]
        }
      }
    }
  }
};

export function buildContentPrompt(request) {
  const languageName = request.language === "en" ? "English" : "Chinese";
  const platform = request.platform || "xiaohongshu";
  const topic = normalizeTopic(request.topic, "product campaign");
  const goal = request.goal || "sell_product";
  const template = request.templateName || "no template";
  const templateHint = request.templatePromptHint || "none";
  const brand = request.brandName || "none";
  const brandIndustry = request.brandIndustry || "none";
  const bannedWords = request.bannedWords || "none";

  return [
    `You are ViralForge, an expert short-form social content strategist.`,
    `Generate a ${languageName} content package for ${platform}.`,
    `Goal: ${goal}.`,
    `Topic or product: ${topic}.`,
    `NON-NEGOTIABLE TOPIC ANCHOR: every title, hook, caption, selling point, hashtag idea, and poster field must be about this exact topic/product.`,
    `Do not replace, reinterpret, or substitute the topic/product with another item. If the topic combines product and audience, keep the product as the main subject.`,
    `The poster headline or subtitle must include the exact topic/product wording, unless that would be too long; in that case include the core product phrase.`,
    `Audience: ${request.audience || "general audience"}.`,
    `Tone: ${request.tone || "clear, practical, non-exaggerated"}.`,
    `Brand: ${brand}.`,
    `Brand industry: ${brandIndustry}.`,
    `Banned words, claims, or angles: ${bannedWords}.`,
    `Template: ${template}.`,
    `Template hint: ${templateHint}.`,
    `Return only one JSON object with exactly these top-level keys: titles, hooks, caption, sellingPoints, hashtags, poster.`,
    `titles must be an array of at least 3 objects: {"text":"...","score":0-100,"reason":"..."}.`,
    `hooks must be an array of at least 2 objects: {"text":"...","score":0-100,"reason":"..."}.`,
    `caption must be one complete social post string.`,
    `sellingPoints and hashtags must be string arrays.`,
    `poster must be {"headline":"...","subtitle":"...","cta":"...","style":"Clean"}.`,
    `Do not return content_package, slides, markdown, or explanatory text.`,
    `Respect the banned words, claims, and angles exactly. Do not include them or close variants.`,
    `Avoid unverifiable medical, financial, or legal claims.`
  ].join("\n");
}

export function normalizeContentResponse(parsed, request) {
  const normalizedParsed = normalizeAlternateResponse(parsed, request);
  const normalized = {
    titles: normalizeScoredLines(normalizedParsed.titles),
    hooks: normalizeScoredLines(normalizedParsed.hooks),
    caption: String(normalizedParsed.caption ?? ""),
    sellingPoints: Array.isArray(normalizedParsed.sellingPoints) ? normalizedParsed.sellingPoints.map(String) : [],
    hashtags: Array.isArray(normalizedParsed.hashtags) ? normalizedParsed.hashtags.map(String) : [],
    poster: {
      headline: String(normalizedParsed.poster?.headline ?? request.topic ?? "Poster"),
      subtitle: String(normalizedParsed.poster?.subtitle ?? request.topic ?? ""),
      cta: String(normalizedParsed.poster?.cta ?? request.templateName ?? "Learn more"),
      style: normalizePosterStyle(normalizedParsed.poster?.style ?? request.templateStyle)
    }
  };

  return groundContentInTopic(normalized, request);
}

function normalizeAlternateResponse(parsed, request) {
  if (Array.isArray(parsed?.titles) || !Array.isArray(parsed?.content_package)) {
    return parsed ?? {};
  }

  const packages = parsed.content_package;
  const titles = packages
    .map((item) => item?.title)
    .filter(Boolean)
    .map((text) => ({
      text,
      score: 82,
      reason: "Generated by the selected content route."
    }));

  const bodies = packages
    .map((item) => item?.body || item?.caption || item?.slides?.[0]?.caption)
    .filter(Boolean);

  const hooks = bodies.slice(0, 3).map((body) => ({
    text: firstSentence(body),
    score: 80,
    reason: "Derived from the generated content opening."
  }));

  const hashtags = packages.flatMap((item) => normalizeHashtags(item?.hashtags));
  const caption = bodies[0] || titles[0]?.text || "";

  return {
    titles,
    hooks,
    caption,
    sellingPoints: packages
      .map((item) => item?.format || item?.length)
      .filter(Boolean)
      .slice(0, 5),
    hashtags,
    poster: {
      headline: titles[0]?.text || request.topic || "Poster",
      subtitle: request.topic || "",
      cta: request.templateName || "立即查看",
      style: request.templateStyle || "Clean"
    }
  };
}

function firstSentence(value) {
  const text = String(value).replace(/\s+/g, " ").trim();
  const match = text.match(/^(.{1,80}?[。！？.!?])/);
  return match?.[1] ?? text.slice(0, 80);
}

function normalizeHashtags(value) {
  if (Array.isArray(value)) {
    return value.flatMap(normalizeHashtags);
  }
  if (typeof value !== "string") {
    return [];
  }
  return value
    .split(/\s+/)
    .filter((part) => part.startsWith("#"));
}

export function parseContentJSON(rawContent) {
  if (typeof rawContent !== "string") {
    throw new Error("Model response did not include JSON text.");
  }

  const trimmed = rawContent.trim();
  try {
    return JSON.parse(trimmed);
  } catch {
    const fencedMatch = trimmed.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);
    if (fencedMatch?.[1]) {
      return JSON.parse(fencedMatch[1].trim());
    }

    const firstBrace = trimmed.indexOf("{");
    const lastBrace = trimmed.lastIndexOf("}");
    if (firstBrace >= 0 && lastBrace > firstBrace) {
      return JSON.parse(trimmed.slice(firstBrace, lastBrace + 1));
    }

    throw new Error("Model response was not valid JSON.");
  }
}

function scoredLineSchema() {
  return {
    type: "object",
    additionalProperties: false,
    required: ["text", "score", "reason"],
    properties: {
      text: { type: "string" },
      score: {
        type: "integer",
        minimum: 0,
        maximum: 100
      },
      reason: { type: "string" }
    }
  };
}

function normalizeScoredLines(lines) {
  if (!Array.isArray(lines)) {
    return [];
  }

  return lines.map((line) => ({
    text: typeof line === "string" ? line : String(line.text ?? ""),
    score: typeof line === "string" ? 80 : clampScore(line.score),
    reason: typeof line === "string" ? "" : String(line.reason ?? "")
  })).filter((line) => line.text.length > 0);
}

function clampScore(score) {
  const numeric = Number.parseInt(score, 10);
  if (Number.isNaN(numeric)) {
    return 80;
  }
  return Math.max(0, Math.min(100, numeric));
}

function normalizePosterStyle(style) {
  const allowed = new Set(["Clean", "Bold", "Soft", "Editorial"]);
  return allowed.has(style) ? style : "Clean";
}

function groundContentInTopic(content, request) {
  const topic = normalizeTopic(request.topic, "");
  if (!topic) {
    return content;
  }

  const anchor = coreTopicPhrase(topic);
  const language = request.language === "en" ? "en" : "zh";
  const joinedContent = [
    ...content.titles.map((line) => line.text),
    ...content.hooks.map((line) => line.text),
    content.caption,
    ...content.sellingPoints,
    content.poster.headline,
    content.poster.subtitle,
    content.poster.cta
  ].join("\n");

  if (!containsTopicAnchor(joinedContent, topic)) {
    content.titles.unshift(scoredLine(topicTitle(topic, language), 96, "Anchored to the requested topic/product."));
    content.hooks.unshift(scoredLine(topicHook(topic, language), 92, "Anchored to the requested topic/product."));
    content.caption = topicCaption(topic, request, language);
    content.sellingPoints = topicSellingPoints(topic, language);
  }

  if (!containsTopicAnchor(`${content.poster.headline}\n${content.poster.subtitle}`, topic)) {
    content.poster.headline = topicPosterHeadline(anchor, language);
    content.poster.subtitle = topic;
  }

  content.titles = content.titles.slice(0, 5);
  content.hooks = content.hooks.slice(0, 4);
  content.sellingPoints = content.sellingPoints.slice(0, 6);
  return content;
}

function containsTopicAnchor(value, topic) {
  const text = normalizeComparable(value);
  const exact = normalizeComparable(topic);
  if (!exact) {
    return false;
  }
  if (text.includes(exact)) {
    return true;
  }

  const tokens = topicTokens(topic);
  if (tokens.length === 0) {
    return false;
  }
  return tokens.some((token) => text.includes(normalizeComparable(token)));
}

function topicTokens(topic) {
  const text = normalizeTopic(topic, "");
  const latinTokens = text.match(/[a-zA-Z0-9][a-zA-Z0-9-]{2,}/g) ?? [];
  const chineseTokens = text
    .split(/[，,。.!！?？、\s]+/)
    .flatMap((part) => part.match(/[\u4e00-\u9fff]{2,}/g) ?? [])
    .filter((part) => !genericChineseTopicWords().has(part));
  return [...new Set([...latinTokens, ...chineseTokens])];
}

function coreTopicPhrase(topic) {
  return topicTokens(topic)[0] || normalizeTopic(topic, "产品");
}

function normalizeTopic(value, fallback) {
  if (typeof value !== "string") {
    return fallback;
  }
  const trimmed = value.replace(/\s+/g, " ").trim();
  if (!trimmed || /^[\p{P}\p{S}\s]+$/u.test(trimmed)) {
    return fallback;
  }
  return trimmed;
}

function normalizeComparable(value) {
  return String(value ?? "")
    .toLowerCase()
    .replace(/\s+/g, "")
    .replace(/[^\p{L}\p{N}\u4e00-\u9fff]+/gu, "");
}

function genericChineseTopicWords() {
  return new Set(["适合", "上班族", "女生", "男生", "人群", "产品", "主题"]);
}

function scoredLine(text, score, reason) {
  return { text, score, reason };
}

function topicTitle(topic, language) {
  if (language === "en") {
    return `Is this ${topic} actually worth it?`;
  }
  return `${topic}到底值不值得入手？`;
}

function topicHook(topic, language) {
  if (language === "en") {
    return `Before buying ${topic}, look at the real use scenario first.`;
  }
  return `买${topic}之前，先看它到底解决哪个真实场景。`;
}

function topicCaption(topic, request, language) {
  const audience = request.audience ? String(request.audience) : "";
  if (language === "en") {
    return `A practical look at ${topic}${audience ? ` for ${audience}` : ""}: where it helps, when it is useful, and what to check before buying.`;
  }
  return `这次围绕${topic}${audience ? `和${audience}` : ""}做一次真实种草：它适合什么场景、解决什么小麻烦、入手前要看哪些细节。`;
}

function topicSellingPoints(topic, language) {
  if (language === "en") {
    return [`Use case for ${topic}`, "Daily convenience", "Easy decision points", "Practical buying checklist"];
  }
  return [`${topic}的核心使用场景`, "日常使用更省事", "适合做购买决策对比", "卖点表达清晰不夸张"];
}

function topicPosterHeadline(anchor, language) {
  if (language === "en") {
    return `${anchor}: practical and easy to use`;
  }
  return `${anchor}，好用才值得种草`;
}
